// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policytap.proto

/*
Package dnstap is a generated protocol buffer package.

It is generated from these files:
	policytap.proto

It has these top-level messages:
	DnstapAttribute
	Extra
*/
package dnstap

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// PolicyAction defines available policy action type
type PolicyAction int32

const (
	PolicyAction_DENY        PolicyAction = 1
	PolicyAction_PASSTHROUGH PolicyAction = 2
	PolicyAction_NXDOMAIN    PolicyAction = 3
	PolicyAction_REDIRECT    PolicyAction = 4
	PolicyAction_REFUSE      PolicyAction = 5
)

var PolicyAction_name = map[int32]string{
	1: "DENY",
	2: "PASSTHROUGH",
	3: "NXDOMAIN",
	4: "REDIRECT",
	5: "REFUSE",
}
var PolicyAction_value = map[string]int32{
	"DENY":        1,
	"PASSTHROUGH": 2,
	"NXDOMAIN":    3,
	"REDIRECT":    4,
	"REFUSE":      5,
}

func (x PolicyAction) Enum() *PolicyAction {
	p := new(PolicyAction)
	*p = x
	return p
}
func (x PolicyAction) String() string {
	return proto.EnumName(PolicyAction_name, int32(x))
}
func (x *PolicyAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PolicyAction_value, data, "PolicyAction")
	if err != nil {
		return err
	}
	*x = PolicyAction(value)
	return nil
}
func (PolicyAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DnstapAttribute struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Value            []byte  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DnstapAttribute) Reset()                    { *m = DnstapAttribute{} }
func (m *DnstapAttribute) String() string            { return proto.CompactTextString(m) }
func (*DnstapAttribute) ProtoMessage()               {}
func (*DnstapAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DnstapAttribute) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *DnstapAttribute) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Extra struct {
	Attrs            []*DnstapAttribute `protobuf:"bytes,1,rep,name=attrs" json:"attrs,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Extra) Reset()                    { *m = Extra{} }
func (m *Extra) String() string            { return proto.CompactTextString(m) }
func (*Extra) ProtoMessage()               {}
func (*Extra) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Extra) GetAttrs() []*DnstapAttribute {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func init() {
	proto.RegisterType((*DnstapAttribute)(nil), "dnstap.DnstapAttribute")
	proto.RegisterType((*Extra)(nil), "dnstap.Extra")
	proto.RegisterEnum("dnstap.PolicyAction", PolicyAction_name, PolicyAction_value)
}

func init() { proto.RegisterFile("policytap.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0x69, 0xb6, 0x8c, 0xf9, 0x56, 0x6c, 0x78, 0x08, 0xf6, 0x58, 0x76, 0x2a, 0x82, 0x3d,
	0x78, 0xd0, 0x73, 0x30, 0xd1, 0xed, 0x60, 0x37, 0xd3, 0x0d, 0xf4, 0x18, 0xd7, 0x1d, 0x02, 0x63,
	0x09, 0xe9, 0xab, 0xe8, 0x7f, 0x2f, 0xb6, 0xb7, 0xdd, 0x7e, 0x1f, 0xfc, 0xf8, 0xf8, 0x20, 0x0b,
	0xfe, 0xe4, 0x0e, 0xbf, 0x64, 0x43, 0x15, 0xa2, 0x27, 0x8f, 0xb3, 0xf6, 0xdc, 0x91, 0x0d, 0xcb,
	0x27, 0xc8, 0xd4, 0xb0, 0x24, 0x51, 0x74, 0x5f, 0x3d, 0x1d, 0xf1, 0x1a, 0x98, 0x6b, 0xf3, 0xa4,
	0x60, 0xe5, 0x95, 0x61, 0xae, 0xc5, 0x1b, 0xe0, 0xdf, 0xf6, 0xd4, 0x1f, 0x73, 0x56, 0xb0, 0x32,
	0x35, 0x23, 0x2c, 0x1f, 0x81, 0xeb, 0x1f, 0x8a, 0x16, 0xef, 0x81, 0x5b, 0xa2, 0xd8, 0xe5, 0x49,
	0x31, 0x29, 0x17, 0x0f, 0xb7, 0xd5, 0x68, 0xae, 0x2e, 0xb4, 0x66, 0x7c, 0xdd, 0xbd, 0x43, 0xba,
	0x1d, 0x5a, 0xe4, 0x81, 0x9c, 0x3f, 0xe3, 0x1c, 0xa6, 0x4a, 0xd7, 0x9f, 0x22, 0xc1, 0x0c, 0x16,
	0x5b, 0xd9, 0x34, 0xbb, 0x95, 0xd9, 0xec, 0x5f, 0x57, 0x82, 0x61, 0x0a, 0xf3, 0xfa, 0x43, 0x6d,
	0xde, 0xe4, 0xba, 0x16, 0x93, 0x7f, 0x32, 0x5a, 0xad, 0x8d, 0x7e, 0xde, 0x89, 0x29, 0x02, 0xcc,
	0x8c, 0x7e, 0xd9, 0x37, 0x5a, 0xf0, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0xf7, 0xb7, 0x91,
	0xdd, 0x00, 0x00, 0x00,
}
