// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Attribute
	Request
	Response
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_OK               Response_Status = 0
	Response_NOTFOUND         Response_Status = 1
	Response_INSUFFICIENTDATA Response_Status = 2
	Response_NOTAPPLICABLE    Response_Status = 3
	Response_GENERALERROR     Response_Status = 4
	Response_SERVICEERROR     Response_Status = 5
	Response_FATALERROR       Response_Status = 6
)

var Response_Status_name = map[int32]string{
	0: "OK",
	1: "NOTFOUND",
	2: "INSUFFICIENTDATA",
	3: "NOTAPPLICABLE",
	4: "GENERALERROR",
	5: "SERVICEERROR",
	6: "FATALERROR",
}
var Response_Status_value = map[string]int32{
	"OK":               0,
	"NOTFOUND":         1,
	"INSUFFICIENTDATA": 2,
	"NOTAPPLICABLE":    3,
	"GENERALERROR":     4,
	"SERVICEERROR":     5,
	"FATALERROR":       6,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Attribute struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type  int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Attribute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Attribute) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Attribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Request struct {
	QueryType  string       `protobuf:"bytes,1,opt,name=query_type,json=queryType" json:"query_type,omitempty"`
	Attributes []*Attribute `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetQueryType() string {
	if m != nil {
		return m.QueryType
	}
	return ""
}

func (m *Request) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Response struct {
	Status Response_Status `protobuf:"varint,1,opt,name=status,enum=service.Response_Status" json:"status,omitempty"`
	Values []*Attribute    `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_OK
}

func (m *Response) GetValues() []*Attribute {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Attribute)(nil), "service.Attribute")
	proto.RegisterType((*Request)(nil), "service.Request")
	proto.RegisterType((*Response)(nil), "service.Response")
	proto.RegisterEnum("service.Response_Status", Response_Status_name, Response_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PIP service

type PIPClient interface {
	GetAttribute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type pIPClient struct {
	cc *grpc.ClientConn
}

func NewPIPClient(cc *grpc.ClientConn) PIPClient {
	return &pIPClient{cc}
}

func (c *pIPClient) GetAttribute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/service.PIP/GetAttribute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PIP service

type PIPServer interface {
	GetAttribute(context.Context, *Request) (*Response, error)
}

func RegisterPIPServer(s *grpc.Server, srv PIPServer) {
	s.RegisterService(&_PIP_serviceDesc, srv)
}

func _PIP_GetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PIPServer).GetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.PIP/GetAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PIPServer).GetAttribute(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PIP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.PIP",
	HandlerType: (*PIPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAttribute",
			Handler:    _PIP_GetAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x6b, 0xc2, 0x40,
	0x10, 0x85, 0x4d, 0xa2, 0x51, 0xa7, 0x2a, 0xeb, 0xe0, 0x21, 0x14, 0x0a, 0x92, 0x93, 0xf4, 0x20,
	0x25, 0xa5, 0xb7, 0x5e, 0xb6, 0xba, 0x91, 0x50, 0x49, 0xc2, 0x1a, 0x7b, 0x2a, 0x14, 0xad, 0x7b,
	0x08, 0x94, 0xaa, 0xd9, 0x8d, 0x20, 0xfd, 0xbd, 0xfd, 0x1f, 0xc5, 0x4d, 0x62, 0x85, 0x42, 0x6f,
	0x99, 0x97, 0xef, 0xcd, 0xbc, 0xd9, 0x81, 0xae, 0x14, 0xd9, 0x21, 0x7d, 0x17, 0xe3, 0x5d, 0xb6,
	0x55, 0x5b, 0x6c, 0x96, 0xa5, 0xcb, 0xa0, 0x4d, 0x95, 0xca, 0xd2, 0x75, 0xae, 0x04, 0xf6, 0xc0,
	0x4c, 0x37, 0x8e, 0x31, 0x34, 0x46, 0x6d, 0x6e, 0xa6, 0x1b, 0x44, 0xa8, 0xab, 0xe3, 0x4e, 0x38,
	0xe6, 0xd0, 0x18, 0x35, 0xb8, 0xfe, 0xc6, 0x01, 0x34, 0x0e, 0xab, 0x8f, 0x5c, 0x38, 0x96, 0xc6,
	0x8a, 0xc2, 0x7d, 0x85, 0x26, 0x17, 0xfb, 0x5c, 0x48, 0x85, 0x37, 0x00, 0xfb, 0x5c, 0x64, 0xc7,
	0x37, 0x6d, 0x2d, 0x9a, 0xb5, 0xb5, 0x92, 0x9c, 0xfc, 0x1e, 0xc0, 0xaa, 0x1a, 0x28, 0x1d, 0x73,
	0x68, 0x8d, 0xae, 0x3c, 0x1c, 0x57, 0xe9, 0xce, 0x59, 0xf8, 0x05, 0xe5, 0x7e, 0x1b, 0xd0, 0xe2,
	0x42, 0xee, 0xb6, 0x9f, 0x52, 0xe0, 0x1d, 0xd8, 0x52, 0xad, 0x54, 0x2e, 0x75, 0xef, 0x9e, 0xe7,
	0x9c, 0xcd, 0x15, 0x32, 0x5e, 0xe8, 0xff, 0xbc, 0xe4, 0xf0, 0x16, 0x6c, 0x9d, 0xf2, 0xbf, 0x71,
	0x25, 0xe1, 0x7e, 0x81, 0x5d, 0xb8, 0xd1, 0x06, 0x33, 0x7a, 0x26, 0x35, 0xec, 0x40, 0x2b, 0x8c,
	0x12, 0x3f, 0x5a, 0x86, 0x53, 0x62, 0xe0, 0x00, 0x48, 0x10, 0x2e, 0x96, 0xbe, 0x1f, 0x4c, 0x02,
	0x16, 0x26, 0x53, 0x9a, 0x50, 0x62, 0x62, 0x1f, 0xba, 0x61, 0x94, 0xd0, 0x38, 0x9e, 0x07, 0x13,
	0xfa, 0x34, 0x67, 0xc4, 0x42, 0x02, 0x9d, 0x19, 0x0b, 0x19, 0xa7, 0x73, 0xc6, 0x79, 0xc4, 0x49,
	0xfd, 0xa4, 0x2c, 0x18, 0x7f, 0x09, 0x26, 0xac, 0x50, 0x1a, 0xd8, 0x03, 0xf0, 0x69, 0x52, 0x11,
	0xb6, 0xf7, 0x08, 0x56, 0x1c, 0xc4, 0xf8, 0x00, 0x9d, 0x99, 0x50, 0xbf, 0x67, 0x21, 0x17, 0x1b,
	0xea, 0x37, 0xbe, 0xee, 0xff, 0xd9, 0xd9, 0xad, 0xad, 0x6d, 0x7d, 0xda, 0xfb, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x1f, 0xf3, 0xba, 0x6d, 0xeb, 0x01, 0x00, 0x00,
}
