// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/control.proto

/*
Package control is a generated protocol buffer package.

It is generated from these files:
	proto/control.proto

It has these top-level messages:
	Item
	Chunk
	Update
	Response
*/
package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item_DataType int32

const (
	Item_POLICIES       Item_DataType = 0
	Item_CONTENT        Item_DataType = 1
	Item_POLICIES_PATCH Item_DataType = 2
	Item_CONTENT_PATCH  Item_DataType = 3
)

var Item_DataType_name = map[int32]string{
	0: "POLICIES",
	1: "CONTENT",
	2: "POLICIES_PATCH",
	3: "CONTENT_PATCH",
}
var Item_DataType_value = map[string]int32{
	"POLICIES":       0,
	"CONTENT":        1,
	"POLICIES_PATCH": 2,
	"CONTENT_PATCH":  3,
}

func (x Item_DataType) String() string {
	return proto.EnumName(Item_DataType_name, int32(x))
}
func (Item_DataType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Response_Status int32

const (
	Response_ACK     Response_Status = 0
	Response_ERROR   Response_Status = 1
	Response_VERSION Response_Status = 2
)

var Response_Status_name = map[int32]string{
	0: "ACK",
	1: "ERROR",
	2: "VERSION",
}
var Response_Status_value = map[string]int32{
	"ACK":     0,
	"ERROR":   1,
	"VERSION": 2,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Item struct {
	Type     Item_DataType `protobuf:"varint,1,opt,name=type,enum=control.Item_DataType" json:"type,omitempty"`
	Version  string        `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	DataId   int32         `protobuf:"varint,3,opt,name=dataId" json:"dataId,omitempty"`
	Id       string        `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
	Includes []int32       `protobuf:"varint,5,rep,packed,name=includes" json:"includes,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetType() Item_DataType {
	if m != nil {
		return m.Type
	}
	return Item_POLICIES
}

func (m *Item) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Item) GetDataId() int32 {
	if m != nil {
		return m.DataId
	}
	return 0
}

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetIncludes() []int32 {
	if m != nil {
		return m.Includes
	}
	return nil
}

type Chunk struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Chunk) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Update struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Update) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response struct {
	Status  Response_Status `protobuf:"varint,1,opt,name=status,enum=control.Response_Status" json:"status,omitempty"`
	Id      int32           `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Details string          `protobuf:"bytes,3,opt,name=details" json:"details,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_ACK
}

func (m *Response) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "control.Item")
	proto.RegisterType((*Chunk)(nil), "control.Chunk")
	proto.RegisterType((*Update)(nil), "control.Update")
	proto.RegisterType((*Response)(nil), "control.Response")
	proto.RegisterEnum("control.Item_DataType", Item_DataType_name, Item_DataType_value)
	proto.RegisterEnum("control.Response_Status", Response_Status_name, Response_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PDPControl service

type PDPControlClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (PDPControl_UploadClient, error)
	Parse(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error)
	Apply(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error)
}

type pDPControlClient struct {
	cc *grpc.ClientConn
}

func NewPDPControlClient(cc *grpc.ClientConn) PDPControlClient {
	return &pDPControlClient{cc}
}

func (c *pDPControlClient) Upload(ctx context.Context, opts ...grpc.CallOption) (PDPControl_UploadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PDPControl_serviceDesc.Streams[0], c.cc, "/control.PDPControl/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &pDPControlUploadClient{stream}
	return x, nil
}

type PDPControl_UploadClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type pDPControlUploadClient struct {
	grpc.ClientStream
}

func (x *pDPControlUploadClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pDPControlUploadClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pDPControlClient) Parse(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/control.PDPControl/Parse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pDPControlClient) Apply(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/control.PDPControl/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PDPControl service

type PDPControlServer interface {
	Upload(PDPControl_UploadServer) error
	Parse(context.Context, *Item) (*Response, error)
	Apply(context.Context, *Update) (*Response, error)
}

func RegisterPDPControlServer(s *grpc.Server, srv PDPControlServer) {
	s.RegisterService(&_PDPControl_serviceDesc, srv)
}

func _PDPControl_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PDPControlServer).Upload(&pDPControlUploadServer{stream})
}

type PDPControl_UploadServer interface {
	SendAndClose(*Response) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type pDPControlUploadServer struct {
	grpc.ServerStream
}

func (x *pDPControlUploadServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pDPControlUploadServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PDPControl_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDPControlServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.PDPControl/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDPControlServer).Parse(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _PDPControl_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDPControlServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.PDPControl/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDPControlServer).Apply(ctx, req.(*Update))
	}
	return interceptor(ctx, in, info, handler)
}

var _PDPControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "control.PDPControl",
	HandlerType: (*PDPControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _PDPControl_Parse_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _PDPControl_Apply_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _PDPControl_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/control.proto",
}

func init() { proto.RegisterFile("proto/control.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xd1, 0x8e, 0x93, 0x40,
	0x14, 0x86, 0x3b, 0xb4, 0xd0, 0xf6, 0xe8, 0x22, 0x7b, 0x4c, 0x36, 0x93, 0xf5, 0x86, 0x70, 0x85,
	0x1a, 0x59, 0xb3, 0x3e, 0x41, 0xc3, 0x92, 0x48, 0xdc, 0x14, 0x32, 0x45, 0x6f, 0xcd, 0xb8, 0x33,
	0x89, 0x44, 0x04, 0xc2, 0x4c, 0x4d, 0xfa, 0x18, 0x5e, 0xfa, 0x72, 0x3e, 0x8b, 0x61, 0x3a, 0x90,
	0x98, 0xdd, 0x3b, 0x7e, 0xfe, 0x8f, 0x39, 0xff, 0xf9, 0x19, 0x78, 0xd9, 0x0f, 0x9d, 0xee, 0x6e,
	0x1e, 0xba, 0x56, 0x0f, 0x5d, 0x93, 0x18, 0x85, 0x6b, 0x2b, 0xa3, 0xbf, 0x04, 0x56, 0xb9, 0x96,
	0x3f, 0xf1, 0x0d, 0xac, 0xf4, 0xa9, 0x97, 0x94, 0x84, 0x24, 0xf6, 0x6f, 0xaf, 0x92, 0x89, 0x1f,
	0xcd, 0xe4, 0x8e, 0x6b, 0x5e, 0x9d, 0x7a, 0xc9, 0x0c, 0x83, 0x14, 0xd6, 0xbf, 0xe4, 0xa0, 0xea,
	0xae, 0xa5, 0x4e, 0x48, 0xe2, 0x2d, 0x9b, 0x24, 0x5e, 0x81, 0x27, 0xb8, 0xe6, 0xb9, 0xa0, 0xcb,
	0x90, 0xc4, 0x2e, 0xb3, 0x0a, 0x7d, 0x70, 0x6a, 0x41, 0x57, 0x06, 0x76, 0x6a, 0x81, 0xd7, 0xb0,
	0xa9, 0xdb, 0x87, 0xe6, 0x28, 0xa4, 0xa2, 0x6e, 0xb8, 0x8c, 0x5d, 0x36, 0xeb, 0xe8, 0x1e, 0x36,
	0xd3, 0x3c, 0x7c, 0x0e, 0x9b, 0xb2, 0xb8, 0xcf, 0xd3, 0x3c, 0x3b, 0x04, 0x0b, 0x7c, 0x06, 0xeb,
	0xb4, 0xd8, 0x57, 0xd9, 0xbe, 0x0a, 0x08, 0x22, 0xf8, 0x93, 0xf5, 0xb5, 0xdc, 0x55, 0xe9, 0xc7,
	0xc0, 0xc1, 0x4b, 0xb8, 0xb0, 0x80, 0x7d, 0xb5, 0x8c, 0x5e, 0x81, 0x9b, 0x7e, 0x3f, 0xb6, 0x3f,
	0x10, 0x61, 0x35, 0x86, 0x31, 0x0b, 0x6e, 0x99, 0x79, 0x8e, 0x28, 0x78, 0x9f, 0x7b, 0xc1, 0xb5,
	0xb4, 0x01, 0x89, 0x09, 0xed, 0xd4, 0x22, 0xfa, 0x4d, 0x60, 0xc3, 0xa4, 0xea, 0xbb, 0x56, 0x49,
	0x7c, 0x0f, 0x9e, 0xd2, 0x5c, 0x1f, 0x95, 0x6d, 0x87, 0xce, 0xed, 0x4c, 0x48, 0x72, 0x30, 0x3e,
	0xb3, 0x9c, 0x3d, 0xce, 0x99, 0x8e, 0x1b, 0x1b, 0x13, 0x52, 0xf3, 0xba, 0x51, 0xa6, 0x98, 0x2d,
	0x9b, 0x64, 0xf4, 0x1a, 0xbc, 0xf3, 0xb7, 0xb8, 0x86, 0xe5, 0x2e, 0xfd, 0x14, 0x2c, 0x70, 0x0b,
	0x6e, 0xc6, 0x58, 0xc1, 0x02, 0x32, 0x6e, 0xfc, 0x25, 0x63, 0x87, 0xbc, 0xd8, 0x07, 0xce, 0xed,
	0x1f, 0x02, 0x50, 0xde, 0x95, 0xe9, 0x79, 0x36, 0xde, 0x8c, 0xe1, 0x9b, 0x8e, 0x0b, 0xf4, 0xe7,
	0x3c, 0x66, 0xd5, 0xeb, 0xcb, 0x47, 0xf9, 0xa2, 0x45, 0x4c, 0xf0, 0x2d, 0xb8, 0x25, 0x1f, 0x94,
	0xc4, 0x8b, 0xff, 0xfe, 0xee, 0x93, 0x38, 0xbe, 0x03, 0x77, 0xd7, 0xf7, 0xcd, 0x09, 0x5f, 0xcc,
	0xee, 0xb9, 0xaa, 0x27, 0xf1, 0x6f, 0x9e, 0xb9, 0x57, 0x1f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xca, 0x89, 0xda, 0x96, 0x6e, 0x02, 0x00, 0x00,
}
